error: more high-level printer registration functions
Registering an error printer always requires a similar song-and-dance.
With the introduction of two new printer registration functions, this
is abstracted away.  These functions separate two concerns that every
registration must consider: selecting the exception to display, and
formatting the exception appropriately.  Two distinct functions are
passed into the new-style registration functions to deal with these
concerns respectively.