error: adjust NotImplemented; always print locations
Beluga used to use Camlp4 for its parser, and it used the location
type defined by Camlp4. The printing of this type was not guaranteed
to be stable, so the Beluga test harness disabled location printing to
ensure that the same version of Beluga compiled against different
Camlp4 versions would still produce the same output.

Since Beluga no longer uses Camlp4, the rationale for being able to
disable location printing has vanished. Therefore I've removed the
global variable that determines whether locations will be printed.